Basic to Intermediate

Q1. Retrieve the first name and last name of all customers.

select first_name, last_name from customer 


Q2. Find the total number of invoices in the database.

select count (*) as total_invoices from invoice 


Q3. List all tracks along with their respective album titles.

select track.name as track_name, album.title as album_title 
from track 
join album on track.album_id = album.album_id 


Q4. Find the total sales (sum of total column) from the invoice table.

select sum (total) as total_sales from invoice


Q5. Retrieve all invoices where the total amount is greater than $10.

select * from invoice 
where total < 10


Q6. Get the top 5 most expensive tracks based on unit price.

select name, unit_price from track
order by unit_price DESC
limit 5

Q7. Find all tracks that belong to the ‘Rock’ genre.

select track.name from track
join genre on track.genre_id = genre.genre_id
where genre.name = 'Rock'

Q8. Count the number of customers in each country.

select count (*) country from customer 
group by country 

Q9. Retrieve the names of employees along with their managers’ names.

select e.first_name as employee_name, e.last_name as employee_last, 
m.first_name as manager_name, m.last_name as manager_last
from employee e
left join employee m on e.reports_to = m.employee_id


Q10. Find the total revenue generated by each customer.

select customer.customer_id, customer.first_name, customer.last_name,
sum(invoice.total) as total_spent
from customer 
join invoice on customer.customer_id = invoice.customer_id
group by customer.customer_id, customer.first_name, customer.last_name


